language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: OHZykfIOaGGs6EXi98YVMmQ6w0oz13uPUvc0L/U7icUkZKREhaMMKbdBEwoufQUV6mvqUj8ewKgvaNmYvI5j2KCSxj5qYIdYa5Upk3TufL7RpqHwC0qqdD9Mb3+JSUfoZIAYCX+k+RRfi7kquWjczH/imUeSAtXTHq0chgWZ108=
  - secure: h/tVP/20vXWU+PysYUtX0fw+UDp0aRNUe8AowNFoJWkFOzTLe7euYvvZXlHrv4V/56i2COzPFTFLzU1FzejY0IIo1IFFrIaw3R4ghtfpIQ7Elr/fAY9FMtAq/H2CMwI7S2bUwSWHzbYIcHKXapWTvaiQHqMhG+zemkM1SBPpczo=
